### ISSUE TITLE
Open in New Tab — Page Class

### ISSUE THREAD

**Issue by davidhellmann** [haariga/craft-gonzo#91]
Es wäre super da eine Classe am Body zu haben um paar gezielte Styling Sachen zu machen hier.

**Comment by martinherweg** [comment]
Kann jeder Plugin nutzer selber hinzufügen und nach wunsch benennen, einfach in der `patternlib/index.{html|twig}` an den body hängen.

**Comment by davidhellmann** [comment]
Aber nur für im
neuen Tab geht nicht? Weil die hängt ja auch im iFrame dran die Class. Irgendwas wollt ich machen damit.

**Comment by martinherweg** [comment]
Hm so spontan denke nicht ne, ist halt das gleiche Template das da verwendet wird.
